apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-starter-config
  namespace: k8s-starter-dev
  labels:
    app: k8s-starter # This label is used to identify which application this ConfigMap belongs to.
    environment: development
data:
  SERVER_PORT: "8080"
