apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-starter-deployment
  namespace: k8s-starter-dev
  labels:
    app: k8s-starter # This label is used to identify which application this Deployment belongs to.
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-starter # Find Pods that have this label, and manage them.
  template:
    metadata:
      labels:
        app: k8s-starter # Give every new Pod this label
    spec:
      containers:
        - name: k8s-starter
          image: k8s-starter
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: k8s-starter-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m # 250 millicpu = 0.25 CPU core (guaranteed minimum)
              memory: 256Mi # 256 mebibytes of RAM (guaranteed minimum)
            limits:
              cpu: 500m # 0.5 CPU core (hard cap, container cannot exceed)
              memory: 512Mi # 512 MiB RAM (hard cap, Out Of Memory killed if exceeded)
